export const seoConfig = {
  siteName: '운세미 - 사주, 타로, 꿈해몽',
  siteUrl: 'https://unse.me',
  defaultTitle: '운세미 | 오늘의 운세 · 사주 · 타로 · 꿈해몽',
  defaultDescription: '띠별, 별자리별 오늘의 운세, 궁합, 타로 리딩, 꿈해몽, 사주팔자를 무료로 확인하세요. AI가 분석하는 정확한 운세 서비스.',
  locale: 'ko_KR',
  keywords: [
    '운세',
    '사주',
    '타로',
    '꿈해몽',
    '별자리',
    '궁합',
    '띠별운세',
    '오늘의운세',
    '무료운세',
    'AI운세',
    '사주팔자',
    '운세미',
  ],
  openGraph: {
    type: 'website',
    locale: 'ko_KR',
    url: 'https://unse.me',
    siteName: '운세미',
    title: '운세미 | 오늘의 운세 · 사주 · 타로 · 꿈해몽',
    description: 'AI 기반 무료 운세 서비스. 사주, 타로, 꿈해몽, 별자리 운세를 정확하게 풀어드립니다.',
    image: {
      url: 'https://unse.me/og-image.png',
      width: 1200,
      height: 630,
      alt: '운세미 - AI 무료 운세 서비스',
      type: 'image/png',
    },
  },
  twitter: {
    handle: '@unse_me',
    site: '@unse_me',
    cardType: 'summary_large_image',
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION || '',
    naver: process.env.NEXT_PUBLIC_NAVER_VERIFICATION || '',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
};
