export const seoConfig = {
  siteName: '운세 - 사주, 타로, 꿈 해석',
  siteUrl: 'https://unse.me',
  defaultTitle: '운세 | 사주, 타로, 꿈 해석, 별자리 운세',
  defaultDescription: '2024년 띠별, 별자리별 운세, 궁합, 타로, 꿈 해석, 오늘의 운세를 무료로 확인하세요. 사주팔자 상세 분석도 가능합니다.',
  locale: 'ko_KR',
  keywords: [
    '운세',
    '사주',
    '타로',
    '꿈해석',
    '별자리',
    '궁합',
    '띠별운세',
    '2024년운세',
    '오늘운세',
    '신년운세',
    '토정비결',
    '사주팔자',
    '십간십지',
  ],
  openGraph: {
    type: 'website',
    locale: 'ko_KR',
    url: 'https://unse.me',
    siteName: '운세',
    title: '운세 | 사주, 타로, 꿈 해석',
    description: '사주, 타로, 꿈 해석, 별자리 운세 제공',
    image: {
      url: 'https://unse.me/og-image.jpg',
      width: 1200,
      height: 630,
      alt: '운세 - 사주 타로 운세',
      type: 'image/jpeg',
    },
  },
  twitter: {
    handle: '@unse_me',
    site: '@unse_me',
    cardType: 'summary_large_image',
  },
  verification: {
    google: 'google-site-verification-code-here',
    naver: 'naver-site-verification-code-here',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
};
